### ISSUE TITLE
Entity resolver

### ISSUE THREAD

**Issue by gianvi** [froesmatheus/wit.net#2]
Hi, do you have an example to use your client as entity resolver?

I tryied in this way in my c# bot app:

		public async Task StartAsync(IDialogContext context)
		{
			
			WitAi.Wit wit = new WitAi.Wit(accessToken: "MZZDDALMPKUDQX7TEGSUSHJPUU5I5W4F");
			var r3 = wit.Message("il 22 giugno alle 13");

			foreach (var e in r3.Entities)
			{
				var k = e.Key;
				var v = e.Value;

				await context.PostAsync("WITAI ENTITY KEY: " + k);

				foreach (var val in v)
				{
					await context.PostAsync("WITAI ENTITY TYPE: " + val.Type);
				}
			}
		}

**Comment by froesmatheus** [comment]
Hi, which version of the library are you using? @gianvi

**Comment by gianvi** [comment]
@froesmatheus I'm using wit.ai.net 0.1.1.0 (from nuget)

**Comment by gianvi** [comment]
Mmmh, it's strange: actually the Client is working but when I retrieve a Datetime Entity with TO: ...  and FROM ... it seems doesnt valorize tha values
You can see this kind of entity on https://duckling.wit.ai (IT language) with the query: "prenota sala per il 22 giugno nel pomeriggio"

**Comment by froesmatheus** [comment]
@gianvi You're using a different library. I think you're using this one: https://www.nuget.org/packages/Wit.ai.net/

**Comment by gianvi** [comment]
@froesmatheus  I've checked and I've the right version, but the issue persist.
It is possible that tool is not getting values for composed entities (or hierarchical, I just know their names in Luis) ?

This is the **json** that **Duckling.wit.ai** get me back with "domani pomeriggio":

{ “msg_id”: “0s4YSkvlzlMlH8k29”, "_text": “domani pomeriggio”, “entities”: { “datetime”: [ { “confidence”: 0.99902519427591, “values”: [ { “to”: { “value”: “2017-06-14T20:00:00+02:00”, “grain”: “hour” }, “from”: { “value”: “2017-06-14T13:00:00+02:00”, “grain”: “hour” }, “type”: “interval” } ], “to”: { “value”: “2017-06-14T20:00:00+02:00”, “grain”: “hour” }, “from”: { “value”: “2017-06-14T13:00:00+02:00”, “grain”: “hour” }, “type”: “interval” } ] } }

...and this is **response** in above code, using **getMessage("domani pomeriggio")**:
![cattura_witintervalissue](https://user-images.githubusercontent.com/5868313/27104998-39d7a342-508e-11e7-93d9-8eb4366a5508.JPG)

As you can see I have **Datetime** entity recognized with high confidence, but there is **no FROM and TO sub-entities valorized**

**Comment by froesmatheus** [comment]
No I mean, you said you're using the wit.ai.net 0.1.1.0 but this is not my library. Mine is Wit.NET, I think you should open this issue on https://github.com/valencianok/Wit.ai.net haha

**Comment by gianvi** [comment]
Instead, with basic Datetime entity , retrieved for example with the query "il 21 giugno alle 11.00" tool is correctly answering.

Here the **json** back from **Duckling**:

{ “msg_id”: “066zWQAwqXDF91cjo”, "_text": “il 22 giugno alle 11”, “entities”: { “datetime”: [ { “confidence”: 0.96708812631587, “values”: [ { “value”: “2017-06-22T12:00:00+02:00”, “grain”: “hour”, “type”: “value” }, { “value”: “2018-06-22T12:00:00+02:00”, “grain”: “hour”, “type”: “value” }, { “value”: “2019-06-22T12:00:00+02:00”, “grain”: “hour”, “type”: “value” } ], “value”: “2017-06-22T12:00:00+02:00”, “grain”: “hour”, “type”: “value” } ] } }

And this is my stack, with **correct entity** value:
![cattura_witdatetime](https://user-images.githubusercontent.com/5868313/27105672-b6ad6e2c-5090-11e7-922a-1ef45ee5d750.JPG)

**Comment by gianvi** [comment]
Super Lol!! 
Really sorry...now I will try yours XD

**Comment by gianvi** [comment]
Ok, it works!
Your code it's a bit more difficult to understand for me, but I will start to study it ;) 
The problem is that you have a kind of dynamic list with all the sub-entities.
I leave the code above, maybe you can use it as example for Message api :) (or feel free to remove the conv)
Btw really appreciate it!

**Comment by froesmatheus** [comment]
Oh, thanks :) I'll try to make the code simpler too. If you have any questions or feedback please feel free to open other issues
